language: node_js
node_js:
  - '8'
install: yarn
script:
  - yarn test --coverage
  - yarn lint
  - yarn build
  - yarn doc
deploy:
  provider: script
  script: bash scripts/deploy.sh $RELEASE_NOTES_TOKEN
  on:
    branch: master
