language: node_js
node_js:
- '8'
install: yarn
script:
- yarn test --coverage
- yarn lint
- yarn build
- yarn doc
- yarn codecov
- yarn release-notes publish --scope IjzerenHein --name Firestorter --token RELEASE_NOTES_TOKEN ./CHANGELOG.md
